export interface NutritionProfileRecord {
  id: string;
  user_id: string;
  version: number;
  gender: string;
  birth_date: string;
  height_cm: number | string;
  weight_kg: number | string;
  activity_level: string;
  activity_days_per_week: number;
  goal: string;
  target_weight_kg: number | string;
  goal_duration_weeks: number;
  dietary_preferences: string[];
  disliked_ingredients: string[];
  food_allergies: string[];
  food_intolerances: string[];
  medical_notes: string | null;
  bmr_kcal: number | string;
  tdee_kcal: number | string;
  target_calories_kcal: number | string;
  target_protein_g: number | string;
  target_carbs_g: number | string;
  target_fat_g: number | string;
  formula_code: string;
  formula_version: string;
  is_current: boolean;
  calculated_at: string;
  created_at: string;
}
